//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ewu.Domain.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=139.199.82.204;Initial Catalog=LinJiaoFengJu;Persist Security Info=Tr" +
            "ue;User ID=zxh;MultipleActiveResultSets=True;Connect Timeout=15;Encrypt=False;Tr" +
            "ustServerCertificate=False")]
        public string LinJiaoFengJuConnectionString {
            get {
                return ((string)(this["LinJiaoFengJuConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=139.199.82.204;Initial Catalog=LinJiaoFengJu;Persist Security Info=Tr" +
            "ue;User ID=zxh;Password=526114;MultipleActiveResultSets=True;Connect Timeout=15;" +
            "Encrypt=False;TrustServerCertificate=False")]
        public string LinJiaoFengJuConnectionString1 {
            get {
                return ((string)(this["LinJiaoFengJuConnectionString1"]));
            }
        }
    }
}
