// <auto-generated />
namespace Ewu.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MoreInfoProperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MoreInfoProperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201903300733188_MoreInfoProperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
