#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ewu.Domain.Db
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LinJiaoFengJu")]
	public partial class DeliveryAddressDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertDeliveryAddress(DeliveryAddress instance);
    partial void UpdateDeliveryAddress(DeliveryAddress instance);
    partial void DeleteDeliveryAddress(DeliveryAddress instance);
    #endregion
		
		public DeliveryAddressDataContext() : 
				base(global::Ewu.Domain.Properties.Settings.Default.LinJiaoFengJuConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public DeliveryAddressDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DeliveryAddressDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DeliveryAddressDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DeliveryAddressDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DeliveryAddress> DeliveryAddress
		{
			get
			{
				return this.GetTable<DeliveryAddress>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DeliveryAddress")]
	public partial class DeliveryAddress : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DeliveryAddressUID;
		
		private string _UserUID;
		
		private string _LocationProvince;
		
		private string _LocationCity;
		
		private string _LocationDistrict;
		
		private string _MoreLocation;
		
		private string _PhoneNum;
		
		private string _RealName;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDeliveryAddressUIDChanging(string value);
    partial void OnDeliveryAddressUIDChanged();
    partial void OnUserUIDChanging(string value);
    partial void OnUserUIDChanged();
    partial void OnLocationProvinceChanging(string value);
    partial void OnLocationProvinceChanged();
    partial void OnLocationCityChanging(string value);
    partial void OnLocationCityChanged();
    partial void OnLocationDistrictChanging(string value);
    partial void OnLocationDistrictChanged();
    partial void OnMoreLocationChanging(string value);
    partial void OnMoreLocationChanged();
    partial void OnPhoneNumChanging(string value);
    partial void OnPhoneNumChanged();
    partial void OnRealNameChanging(string value);
    partial void OnRealNameChanged();
    #endregion
		
		public DeliveryAddress()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeliveryAddressUID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DeliveryAddressUID
		{
			get
			{
				return this._DeliveryAddressUID;
			}
			set
			{
				if ((this._DeliveryAddressUID != value))
				{
					this.OnDeliveryAddressUIDChanging(value);
					this.SendPropertyChanging();
					this._DeliveryAddressUID = value;
					this.SendPropertyChanged("DeliveryAddressUID");
					this.OnDeliveryAddressUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserUID", DbType="VarChar(50)")]
		public string UserUID
		{
			get
			{
				return this._UserUID;
			}
			set
			{
				if ((this._UserUID != value))
				{
					this.OnUserUIDChanging(value);
					this.SendPropertyChanging();
					this._UserUID = value;
					this.SendPropertyChanged("UserUID");
					this.OnUserUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationProvince", DbType="NVarChar(50)")]
		public string LocationProvince
		{
			get
			{
				return this._LocationProvince;
			}
			set
			{
				if ((this._LocationProvince != value))
				{
					this.OnLocationProvinceChanging(value);
					this.SendPropertyChanging();
					this._LocationProvince = value;
					this.SendPropertyChanged("LocationProvince");
					this.OnLocationProvinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationCity", DbType="NVarChar(50)")]
		public string LocationCity
		{
			get
			{
				return this._LocationCity;
			}
			set
			{
				if ((this._LocationCity != value))
				{
					this.OnLocationCityChanging(value);
					this.SendPropertyChanging();
					this._LocationCity = value;
					this.SendPropertyChanged("LocationCity");
					this.OnLocationCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationDistrict", DbType="NVarChar(50)")]
		public string LocationDistrict
		{
			get
			{
				return this._LocationDistrict;
			}
			set
			{
				if ((this._LocationDistrict != value))
				{
					this.OnLocationDistrictChanging(value);
					this.SendPropertyChanging();
					this._LocationDistrict = value;
					this.SendPropertyChanged("LocationDistrict");
					this.OnLocationDistrictChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoreLocation", DbType="NVarChar(MAX)")]
		public string MoreLocation
		{
			get
			{
				return this._MoreLocation;
			}
			set
			{
				if ((this._MoreLocation != value))
				{
					this.OnMoreLocationChanging(value);
					this.SendPropertyChanging();
					this._MoreLocation = value;
					this.SendPropertyChanged("MoreLocation");
					this.OnMoreLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNum", DbType="NVarChar(50)")]
		public string PhoneNum
		{
			get
			{
				return this._PhoneNum;
			}
			set
			{
				if ((this._PhoneNum != value))
				{
					this.OnPhoneNumChanging(value);
					this.SendPropertyChanging();
					this._PhoneNum = value;
					this.SendPropertyChanged("PhoneNum");
					this.OnPhoneNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealName", DbType="NVarChar(50)")]
		public string RealName
		{
			get
			{
				return this._RealName;
			}
			set
			{
				if ((this._RealName != value))
				{
					this.OnRealNameChanging(value);
					this.SendPropertyChanging();
					this._RealName = value;
					this.SendPropertyChanged("RealName");
					this.OnRealNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
