#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ewu.Domain.Db
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LinJiaoFengJu")]
	public partial class TreasureDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertTreasures(Treasures instance);
    partial void UpdateTreasures(Treasures instance);
    partial void DeleteTreasures(Treasures instance);
    #endregion
		
		public TreasureDataContext() : 
				base(global::Ewu.Domain.Properties.Settings.Default.LinJiaoFengJuConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public TreasureDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TreasureDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TreasureDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TreasureDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Treasures> Treasures
		{
			get
			{
				return this.GetTable<Treasures>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Treasures")]
	public partial class Treasures : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _TreasureUID;
		
		private string _HolderID;
		
		private string _DLogUID;
		
		private string _TreasureName;
		
		private string _TreasureType;
		
		private string _DamageDegree;
		
		private string _TradeRange;
		
		private string _Cover;
		
		private string _DetailPic;
		
		private string _DetailContent;
		
		private string _LocationProvince;
		
		private string _LocationCity;
		
		private string _LocationDistrict;
		
		private System.DateTime _UploadTime;
		
		private System.DateTime _UpdateTime;
		
		private System.Nullable<int> _EditCount;
		
		private int _Favorite;
		
		private string _Link;
		
		private int _BrowseNum;
		
		private string _Remarks;
		
		private System.Data.Linq.Binary _ImageData;
		
		private string _ImageMimeType;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTreasureUIDChanging(System.Guid value);
    partial void OnTreasureUIDChanged();
    partial void OnHolderIDChanging(string value);
    partial void OnHolderIDChanged();
    partial void OnDLogUIDChanging(string value);
    partial void OnDLogUIDChanged();
    partial void OnTreasureNameChanging(string value);
    partial void OnTreasureNameChanged();
    partial void OnTreasureTypeChanging(string value);
    partial void OnTreasureTypeChanged();
    partial void OnDamageDegreeChanging(string value);
    partial void OnDamageDegreeChanged();
    partial void OnTradeRangeChanging(string value);
    partial void OnTradeRangeChanged();
    partial void OnCoverChanging(string value);
    partial void OnCoverChanged();
    partial void OnDetailPicChanging(string value);
    partial void OnDetailPicChanged();
    partial void OnDetailContentChanging(string value);
    partial void OnDetailContentChanged();
    partial void OnLocationProvinceChanging(string value);
    partial void OnLocationProvinceChanged();
    partial void OnLocationCityChanging(string value);
    partial void OnLocationCityChanged();
    partial void OnLocationDistrictChanging(string value);
    partial void OnLocationDistrictChanged();
    partial void OnUploadTimeChanging(System.DateTime value);
    partial void OnUploadTimeChanged();
    partial void OnUpdateTimeChanging(System.DateTime value);
    partial void OnUpdateTimeChanged();
    partial void OnEditCountChanging(System.Nullable<int> value);
    partial void OnEditCountChanged();
    partial void OnFavoriteChanging(int value);
    partial void OnFavoriteChanged();
    partial void OnLinkChanging(string value);
    partial void OnLinkChanged();
    partial void OnBrowseNumChanging(int value);
    partial void OnBrowseNumChanged();
    partial void OnRemarksChanging(string value);
    partial void OnRemarksChanged();
    partial void OnImageDataChanging(System.Data.Linq.Binary value);
    partial void OnImageDataChanged();
    partial void OnImageMimeTypeChanging(string value);
    partial void OnImageMimeTypeChanged();
    #endregion
		
		public Treasures()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TreasureUID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid TreasureUID
		{
			get
			{
				return this._TreasureUID;
			}
			set
			{
				if ((this._TreasureUID != value))
				{
					this.OnTreasureUIDChanging(value);
					this.SendPropertyChanging();
					this._TreasureUID = value;
					this.SendPropertyChanged("TreasureUID");
					this.OnTreasureUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HolderID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string HolderID
		{
			get
			{
				return this._HolderID;
			}
			set
			{
				if ((this._HolderID != value))
				{
					this.OnHolderIDChanging(value);
					this.SendPropertyChanging();
					this._HolderID = value;
					this.SendPropertyChanged("HolderID");
					this.OnHolderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DLogUID", DbType="VarChar(50)")]
		public string DLogUID
		{
			get
			{
				return this._DLogUID;
			}
			set
			{
				if ((this._DLogUID != value))
				{
					this.OnDLogUIDChanging(value);
					this.SendPropertyChanging();
					this._DLogUID = value;
					this.SendPropertyChanged("DLogUID");
					this.OnDLogUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TreasureName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TreasureName
		{
			get
			{
				return this._TreasureName;
			}
			set
			{
				if ((this._TreasureName != value))
				{
					this.OnTreasureNameChanging(value);
					this.SendPropertyChanging();
					this._TreasureName = value;
					this.SendPropertyChanged("TreasureName");
					this.OnTreasureNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TreasureType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TreasureType
		{
			get
			{
				return this._TreasureType;
			}
			set
			{
				if ((this._TreasureType != value))
				{
					this.OnTreasureTypeChanging(value);
					this.SendPropertyChanging();
					this._TreasureType = value;
					this.SendPropertyChanged("TreasureType");
					this.OnTreasureTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DamageDegree", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DamageDegree
		{
			get
			{
				return this._DamageDegree;
			}
			set
			{
				if ((this._DamageDegree != value))
				{
					this.OnDamageDegreeChanging(value);
					this.SendPropertyChanging();
					this._DamageDegree = value;
					this.SendPropertyChanged("DamageDegree");
					this.OnDamageDegreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TradeRange", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TradeRange
		{
			get
			{
				return this._TradeRange;
			}
			set
			{
				if ((this._TradeRange != value))
				{
					this.OnTradeRangeChanging(value);
					this.SendPropertyChanging();
					this._TradeRange = value;
					this.SendPropertyChanged("TradeRange");
					this.OnTradeRangeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cover", DbType="NVarChar(MAX)")]
		public string Cover
		{
			get
			{
				return this._Cover;
			}
			set
			{
				if ((this._Cover != value))
				{
					this.OnCoverChanging(value);
					this.SendPropertyChanging();
					this._Cover = value;
					this.SendPropertyChanged("Cover");
					this.OnCoverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailPic", DbType="NVarChar(MAX)")]
		public string DetailPic
		{
			get
			{
				return this._DetailPic;
			}
			set
			{
				if ((this._DetailPic != value))
				{
					this.OnDetailPicChanging(value);
					this.SendPropertyChanging();
					this._DetailPic = value;
					this.SendPropertyChanged("DetailPic");
					this.OnDetailPicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailContent", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DetailContent
		{
			get
			{
				return this._DetailContent;
			}
			set
			{
				if ((this._DetailContent != value))
				{
					this.OnDetailContentChanging(value);
					this.SendPropertyChanging();
					this._DetailContent = value;
					this.SendPropertyChanged("DetailContent");
					this.OnDetailContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationProvince", DbType="NVarChar(50)")]
		public string LocationProvince
		{
			get
			{
				return this._LocationProvince;
			}
			set
			{
				if ((this._LocationProvince != value))
				{
					this.OnLocationProvinceChanging(value);
					this.SendPropertyChanging();
					this._LocationProvince = value;
					this.SendPropertyChanged("LocationProvince");
					this.OnLocationProvinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationCity", DbType="NVarChar(50)")]
		public string LocationCity
		{
			get
			{
				return this._LocationCity;
			}
			set
			{
				if ((this._LocationCity != value))
				{
					this.OnLocationCityChanging(value);
					this.SendPropertyChanging();
					this._LocationCity = value;
					this.SendPropertyChanged("LocationCity");
					this.OnLocationCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationDistrict", DbType="NVarChar(50)")]
		public string LocationDistrict
		{
			get
			{
				return this._LocationDistrict;
			}
			set
			{
				if ((this._LocationDistrict != value))
				{
					this.OnLocationDistrictChanging(value);
					this.SendPropertyChanging();
					this._LocationDistrict = value;
					this.SendPropertyChanged("LocationDistrict");
					this.OnLocationDistrictChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UploadTime", DbType="DateTime NOT NULL")]
		public System.DateTime UploadTime
		{
			get
			{
				return this._UploadTime;
			}
			set
			{
				if ((this._UploadTime != value))
				{
					this.OnUploadTimeChanging(value);
					this.SendPropertyChanging();
					this._UploadTime = value;
					this.SendPropertyChanged("UploadTime");
					this.OnUploadTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateTime", DbType="DateTime NOT NULL")]
		public System.DateTime UpdateTime
		{
			get
			{
				return this._UpdateTime;
			}
			set
			{
				if ((this._UpdateTime != value))
				{
					this.OnUpdateTimeChanging(value);
					this.SendPropertyChanging();
					this._UpdateTime = value;
					this.SendPropertyChanged("UpdateTime");
					this.OnUpdateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditCount", DbType="Int")]
		public System.Nullable<int> EditCount
		{
			get
			{
				return this._EditCount;
			}
			set
			{
				if ((this._EditCount != value))
				{
					this.OnEditCountChanging(value);
					this.SendPropertyChanging();
					this._EditCount = value;
					this.SendPropertyChanged("EditCount");
					this.OnEditCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Favorite", DbType="Int NOT NULL")]
		public int Favorite
		{
			get
			{
				return this._Favorite;
			}
			set
			{
				if ((this._Favorite != value))
				{
					this.OnFavoriteChanging(value);
					this.SendPropertyChanging();
					this._Favorite = value;
					this.SendPropertyChanged("Favorite");
					this.OnFavoriteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="VarChar(MAX)")]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this.OnLinkChanging(value);
					this.SendPropertyChanging();
					this._Link = value;
					this.SendPropertyChanged("Link");
					this.OnLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrowseNum", DbType="Int NOT NULL")]
		public int BrowseNum
		{
			get
			{
				return this._BrowseNum;
			}
			set
			{
				if ((this._BrowseNum != value))
				{
					this.OnBrowseNumChanging(value);
					this.SendPropertyChanging();
					this._BrowseNum = value;
					this.SendPropertyChanged("BrowseNum");
					this.OnBrowseNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="NVarChar(MAX)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this.OnRemarksChanging(value);
					this.SendPropertyChanging();
					this._Remarks = value;
					this.SendPropertyChanged("Remarks");
					this.OnRemarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageData", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ImageData
		{
			get
			{
				return this._ImageData;
			}
			set
			{
				if ((this._ImageData != value))
				{
					this.OnImageDataChanging(value);
					this.SendPropertyChanging();
					this._ImageData = value;
					this.SendPropertyChanged("ImageData");
					this.OnImageDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageMimeType", DbType="VarChar(50)")]
		public string ImageMimeType
		{
			get
			{
				return this._ImageMimeType;
			}
			set
			{
				if ((this._ImageMimeType != value))
				{
					this.OnImageMimeTypeChanging(value);
					this.SendPropertyChanging();
					this._ImageMimeType = value;
					this.SendPropertyChanged("ImageMimeType");
					this.OnImageMimeTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
